[WinEventLog://Microsoft-Windows-Sysmon/Operational]
index = main
sourcetype = WinEventLog:Microsoft-Windows-Sysmon/Operational
disabled = false

[WinEventLog://Microsoft-Windows-PowerShell/Operational]
index = main
sourcetype = WinEventLog:Microsoft-Windows-PowerShell/Operational
disabled = false

[WinEventLog://Security]
index = main
sourcetype = WinEventLog:Security
disabled = false

[monitor://C:\YaraLogs\yara_matches.log]
index = main
sourcetype = yara_alerts
disabled = false